color0 #504348
color1 #ffb4ab
color2 #fdb0d3
color3 #e0bdcb
color4 #f2bb99
color5 #fdb0d3
color6 #e0bdcb
color7 #eedfe3
color8 #9d8d92
color9 #ffb4ab
color10 #fdb0d3
color11 #e0bdcb
color12 #f2bb99
color13 #fdb0d3
color14 #e0bdcb
color15 #eedfe3

cursor                #eedfe3
cursor_text_color     #191114
background            #191114
foreground            #eedfe3
selection_foreground  #d4c2c8
selection_background  #504348
active_border_color   #fdb0d3
inactive_border_color #504348
url_color             #fdb0d3

active_tab_foreground   #521d3a
active_tab_background   #fdb0d3
inactive_tab_foreground #d4c2c8
inactive_tab_background #504348
cursor_trail_color      #d4c2c8
